services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brightside\Embedassets\ViewHelpers\Asset\CssViewHelper:
    public: true

  Brightside\Embedassets\ViewHelpers\Asset\ScriptViewHelper:
    public: true
