services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Brightside\Embedassets\Xclass\CssViewHelper:
    public: true

  Brightside\Embedassets\Xclass\ScriptViewHelper:
    public: true
